### PR TITLE
fixed classpath errors.

### PR DESCRIPTION
**Pull request by PocketKiller**
I've fixed the problem in the classpath (the w letter in the name of the folder was capital but it was not known at the main section in plugin.yml.)

### CODE REVIEW

**Comment by PEMapModder** [comment]
The proper way to fix this is to change the folder name.

**Comment by TahaTheHacker** [comment]
ya but what about the CAPITAL W??? in the plugin.yml it doesn't have it as a capital letter.

**Comment by PEMapModder** [comment]
It is currently small letter everywhere except in the folder name.

**Comment by TahaTheHacker** [comment]
i know.so i was fixing it.

**Comment by TahaTheHacker** [comment]
and it worked. this supposed to be merged.

**Comment by PEMapModder** [comment]
@TahaTheHacker now the namespaces are inconsistent. Although it works, it's worse.

**Comment by TahaTheHacker** [comment]
How? it worked for me, maybe she changed something?

**Comment by PEMapModder** [comment]
@TahaTheHacker it works but it is not good. #4 is better.

**Comment by TahaTheHacker** [comment]
yaa

**Comment by TahaTheHacker** [comment]
anyway sorry for annoying..

**Pull request closed without merging**
